/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as AppLayoutRouteRouteImport } from './pages/_appLayout/route'
import { Route as AuthLayoutRouteRouteImport } from './pages/_authLayout/route'
import { Route as AppLayoutDashboardIndexRouteImport } from './pages/_appLayout/dashboard/index'
import { Route as AppLayoutEventsIndexRouteImport } from './pages/_appLayout/events/index'
import { Route as AppLayoutHelpCenterIndexRouteImport } from './pages/_appLayout/help-center/index'
import { Route as AppLayoutMembershipIndexRouteImport } from './pages/_appLayout/membership/index'
import { Route as AppLayoutProgramsIndexRouteImport } from './pages/_appLayout/programs/index'
import { Route as AppLayoutStudyMaterialsIndexRouteImport } from './pages/_appLayout/study-materials/index'
import { Route as AuthLayoutLoginIndexRouteImport } from './pages/_authLayout/Login/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRouteRoute = AppLayoutRouteRouteImport.update({
  id: '/_appLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLayoutRouteRoute = AuthLayoutRouteRouteImport.update({
  id: '/_authLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutDashboardIndexRoute = AppLayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutEventsIndexRoute = AppLayoutEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutHelpCenterIndexRoute =
  AppLayoutHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AppLayoutRouteRoute,
  } as any)
const AppLayoutMembershipIndexRoute =
  AppLayoutMembershipIndexRouteImport.update({
    id: '/membership/',
    path: '/membership/',
    getParentRoute: () => AppLayoutRouteRoute,
  } as any)
const AppLayoutProgramsIndexRoute = AppLayoutProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => AppLayoutRouteRoute,
} as any)
const AppLayoutStudyMaterialsIndexRoute =
  AppLayoutStudyMaterialsIndexRouteImport.update({
    id: '/study-materials/',
    path: '/study-materials/',
    getParentRoute: () => AppLayoutRouteRoute,
  } as any)
const AuthLayoutLoginIndexRoute = AuthLayoutLoginIndexRouteImport.update({
  id: '/Login/',
  path: '/Login/',
  getParentRoute: () => AuthLayoutRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/': typeof AppLayoutDashboardIndexRoute
  '/events/': typeof AppLayoutEventsIndexRoute
  '/help-center/': typeof AppLayoutHelpCenterIndexRoute
  '/membership/': typeof AppLayoutMembershipIndexRoute
  '/programs/': typeof AppLayoutProgramsIndexRoute
  '/study-materials/': typeof AppLayoutStudyMaterialsIndexRoute
  '/Login/': typeof AuthLayoutLoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppLayoutDashboardIndexRoute
  '/events': typeof AppLayoutEventsIndexRoute
  '/help-center': typeof AppLayoutHelpCenterIndexRoute
  '/membership': typeof AppLayoutMembershipIndexRoute
  '/programs': typeof AppLayoutProgramsIndexRoute
  '/study-materials': typeof AppLayoutStudyMaterialsIndexRoute
  '/Login': typeof AuthLayoutLoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_appLayout': typeof AppLayoutRouteRouteWithChildren
  '/_authLayout': typeof AuthLayoutRouteRouteWithChildren
  '/_appLayout/dashboard/': typeof AppLayoutDashboardIndexRoute
  '/_appLayout/events/': typeof AppLayoutEventsIndexRoute
  '/_appLayout/help-center/': typeof AppLayoutHelpCenterIndexRoute
  '/_appLayout/membership/': typeof AppLayoutMembershipIndexRoute
  '/_appLayout/programs/': typeof AppLayoutProgramsIndexRoute
  '/_appLayout/study-materials/': typeof AppLayoutStudyMaterialsIndexRoute
  '/_authLayout/Login/': typeof AuthLayoutLoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/'
    | '/events/'
    | '/help-center/'
    | '/membership/'
    | '/programs/'
    | '/study-materials/'
    | '/Login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/events'
    | '/help-center'
    | '/membership'
    | '/programs'
    | '/study-materials'
    | '/Login'
  id:
    | '__root__'
    | '/'
    | '/_appLayout'
    | '/_authLayout'
    | '/_appLayout/dashboard/'
    | '/_appLayout/events/'
    | '/_appLayout/help-center/'
    | '/_appLayout/membership/'
    | '/_appLayout/programs/'
    | '/_appLayout/study-materials/'
    | '/_authLayout/Login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRouteRoute: typeof AppLayoutRouteRouteWithChildren
  AuthLayoutRouteRoute: typeof AuthLayoutRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout': {
      id: '/_appLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authLayout': {
      id: '/_authLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthLayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_appLayout/dashboard/': {
      id: '/_appLayout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AppLayoutDashboardIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/events/': {
      id: '/_appLayout/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AppLayoutEventsIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/help-center/': {
      id: '/_appLayout/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AppLayoutHelpCenterIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/membership/': {
      id: '/_appLayout/membership/'
      path: '/membership'
      fullPath: '/membership/'
      preLoaderRoute: typeof AppLayoutMembershipIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/programs/': {
      id: '/_appLayout/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof AppLayoutProgramsIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_appLayout/study-materials/': {
      id: '/_appLayout/study-materials/'
      path: '/study-materials'
      fullPath: '/study-materials/'
      preLoaderRoute: typeof AppLayoutStudyMaterialsIndexRouteImport
      parentRoute: typeof AppLayoutRouteRoute
    }
    '/_authLayout/Login/': {
      id: '/_authLayout/Login/'
      path: '/Login'
      fullPath: '/Login/'
      preLoaderRoute: typeof AuthLayoutLoginIndexRouteImport
      parentRoute: typeof AuthLayoutRouteRoute
    }
  }
}

interface AppLayoutRouteRouteChildren {
  AppLayoutDashboardIndexRoute: typeof AppLayoutDashboardIndexRoute
  AppLayoutEventsIndexRoute: typeof AppLayoutEventsIndexRoute
  AppLayoutHelpCenterIndexRoute: typeof AppLayoutHelpCenterIndexRoute
  AppLayoutMembershipIndexRoute: typeof AppLayoutMembershipIndexRoute
  AppLayoutProgramsIndexRoute: typeof AppLayoutProgramsIndexRoute
  AppLayoutStudyMaterialsIndexRoute: typeof AppLayoutStudyMaterialsIndexRoute
}

const AppLayoutRouteRouteChildren: AppLayoutRouteRouteChildren = {
  AppLayoutDashboardIndexRoute: AppLayoutDashboardIndexRoute,
  AppLayoutEventsIndexRoute: AppLayoutEventsIndexRoute,
  AppLayoutHelpCenterIndexRoute: AppLayoutHelpCenterIndexRoute,
  AppLayoutMembershipIndexRoute: AppLayoutMembershipIndexRoute,
  AppLayoutProgramsIndexRoute: AppLayoutProgramsIndexRoute,
  AppLayoutStudyMaterialsIndexRoute: AppLayoutStudyMaterialsIndexRoute,
}

const AppLayoutRouteRouteWithChildren = AppLayoutRouteRoute._addFileChildren(
  AppLayoutRouteRouteChildren,
)

interface AuthLayoutRouteRouteChildren {
  AuthLayoutLoginIndexRoute: typeof AuthLayoutLoginIndexRoute
}

const AuthLayoutRouteRouteChildren: AuthLayoutRouteRouteChildren = {
  AuthLayoutLoginIndexRoute: AuthLayoutLoginIndexRoute,
}

const AuthLayoutRouteRouteWithChildren = AuthLayoutRouteRoute._addFileChildren(
  AuthLayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRouteRoute: AppLayoutRouteRouteWithChildren,
  AuthLayoutRouteRoute: AuthLayoutRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
